export const $ = (id) => document.getElementById(id);

export const dom = {
  get landingScreen() { return $('landing-screen'); },
  get uiOverlay() { return $('ui-overlay'); },
  get uiWrapper() { return $('ui-wrapper'); },
  get qrScreen() { return $('qr-screen'); },
  get qrControls() { return $('qr-controls-container'); },
  get qrStatusText() { return $('qr-status-text'); },
  get toast() { return $('toast'); },
  get infoToggleBtn() { return $('info-toggle-btn'); },
  get captureBtn() { return $('capture-btn'); },
  get recenterBtn() { return $('recenter-btn'); },
  get historyModal() { return $('history-modal'); },
  get closeHistoryBtn() { return $('close-history-btn'); },
  get cameraError() { return $('camera-error-msg'); },
  get exitArBtn() { return $('exit-ar-btn'); },
  get loadingBarContainer() { return $('loading-bar-container'); },
  get loadingBar() { return $('loading-bar'); },
  get dancerVideo() { return $('dancer-video'); },
  get arCanvas() { return $('ar-canvas'); },
  get arCameraFeed() { return $('ar-camera-feed'); },
  get landingLoader() { return $('landing-loader'); },
  get landingLoaderCircle() { return $('landing-loader-circle'); },
  get landingLoaderPercent() { return $('landing-loader-percent'); },
  get landingLoaderStatus() { return $('landing-loader-status'); },
  get landingCompatCard() { return $('landing-compat-card'); },
  get landingCompatTitle() { return $('landing-compat-title'); },
  get landingCompatDesc() { return $('landing-compat-desc'); },
  get landingCompatAction() { return $('landing-compat-action'); }
};
